version: "3"

services:
  red-app:
    build: ./red-app
    networks:
      - traffic-light
    ports:
      - "3000:3000"

  yellow-app:
    build: ./yellow-app
    networks:
      - traffic-light
    ports:
      - "4000:4000"

  green-app:
    build: ./green-app
    networks:
      - traffic-light
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - red-app
      - yellow-app
      - green-app
    networks:
      - traffic-light

networks:
  traffic-light:
    driver: bridge
